// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGa5L-bD0u0o3vTwW-m7lnSj4Fy-hzPuk',
    appId: '1:55175448719:web:04b5f12133b1ad46dd08fa',
    messagingSenderId: '55175448719',
    projectId: 'calorie-tracker-e3ab4',
    authDomain: 'calorie-tracker-e3ab4.firebaseapp.com',
    storageBucket: 'calorie-tracker-e3ab4.firebasestorage.app',
    measurementId: 'G-81R3PMDPVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPway7w7Nm7U6QBCxiW1IWxc0csDjyax0',
    appId: '1:55175448719:android:14f8f0810da00377dd08fa',
    messagingSenderId: '55175448719',
    projectId: 'calorie-tracker-e3ab4',
    storageBucket: 'calorie-tracker-e3ab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrozIxADmrMWnBEAWXin3N0LvcJL7hKy8',
    appId: '1:55175448719:ios:f124f8893e209a83dd08fa',
    messagingSenderId: '55175448719',
    projectId: 'calorie-tracker-e3ab4',
    storageBucket: 'calorie-tracker-e3ab4.firebasestorage.app',
    iosBundleId: 'com.example.calorieTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrozIxADmrMWnBEAWXin3N0LvcJL7hKy8',
    appId: '1:55175448719:ios:f124f8893e209a83dd08fa',
    messagingSenderId: '55175448719',
    projectId: 'calorie-tracker-e3ab4',
    storageBucket: 'calorie-tracker-e3ab4.firebasestorage.app',
    iosBundleId: 'com.example.calorieTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGa5L-bD0u0o3vTwW-m7lnSj4Fy-hzPuk',
    appId: '1:55175448719:web:0b98d09f1b74e95ddd08fa',
    messagingSenderId: '55175448719',
    projectId: 'calorie-tracker-e3ab4',
    authDomain: 'calorie-tracker-e3ab4.firebaseapp.com',
    storageBucket: 'calorie-tracker-e3ab4.firebasestorage.app',
    measurementId: 'G-YEYR592B81',
  );
}
